version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Adjust the ports as needed

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Adjust the ports as needed
    environment:
      - NEXT_PUBLIC_API_HOSTNAME=http://backend:5000
